# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - main

pool:
  vmImage: 'windows-2019'

steps:


  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      gradleOptions: '-Xmx3072m'
      sonarQubeRunAnalysis: false

  - task: AndroidSigning@3
    inputs:
      apkFiles: '**/*.apk'
      apksignerKeystoreFile: 'key.store'
      apksignerKeystorePassword: 'storepwd'
      apksignerKeystoreAlias: 'key0'
      apksignerKeyPassword: 'apppwd'
      zipalign: false
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      contents: '**/*.apk' 
      targetFolder: '$(build.artifactStagingDirectory)'
      overWrite: true

  - task: PublishBuildArtifacts@1    
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'

